### ISSUE TITLE
Deployment instructions

### ISSUE THREAD

**Issue by bleetube** [apotdevin/NextPay#2]
I don't see any detailed installation instructions.  Here's how far I got:

1. Clone the repo
2. `npm install`
3. `npm run start`, got prompted to run `next build`, so
4. `npm install -g next`
5. `next build`
Next build failed with this: 

```
info  - Compiled successfully
info  - Collecting page data ..node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: Cannot find module 'next/dist/shared/lib/constants.js'
Require stack:
- /home/meeseeks/NextPay/.next/server/pages/_document.js
- /usr/lib/node_modules/next/dist/server/require.js
- /usr/lib/node_modules/next/dist/server/load-components.js
- /usr/lib/node_modules/next/dist/build/utils.js
- /usr/lib/node_modules/next/node_modules/jest-worker/build/workers/processChild.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.44 (/home/meeseeks/NextPay/.next/server/pages/_document.js:100:18)
    at __webpack_require__ (/home/meeseeks/NextPay/.next/server/webpack-runtime.js:25:42)
    at Object.212 (/home/meeseeks/NextPay/.next/server/chunks/572.js:445:18)
    at __webpack_require__ (/home/meeseeks/NextPay/.next/server/webpack-runtime.js:25:42)
    at Object.572 (/home/meeseeks/NextPay/.next/server/chunks/572.js:1098:18)
    at __webpack_require__ (/home/meeseeks/NextPay/.next/server/webpack-runtime.js:25:42) {
  type: 'Error',
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/meeseeks/NextPay/.next/server/pages/_document.js',
    '/usr/lib/node_modules/next/dist/server/require.js',
    '/usr/lib/node_modules/next/dist/server/load-components.js',
    '/usr/lib/node_modules/next/dist/build/utils.js',
    '/usr/lib/node_modules/next/node_modules/jest-worker/build/workers/processChild.js'
  ]
}

$ next --version
Next.js v11.1.0
$ npm --version
7.20.3
$ node --version
v16.6.2
```
Further steps might also include examples for generating the hex macaroon, e.g.
```
lncli bakemacaroon --save_to=lnurl.macaroon invoices:write
xxd -c2048 -p ~/lnurl.macaroon
```

**Comment by apotdevin** [comment]
Hey! good point, want to create a steps documentation for the README?

Steps should be something along the lines of:
1. npm install
2. npm run build
3. npm run start
